services:
  kestra:
    container_name: javascript-sdk-test-kestra
    image: "europe-west1-docker.pkg.dev/kestra-host/docker/kestra-ee:${KESTRA_VERSION}-no-plugins"
    pull_policy: always
    user: "root"
    command: server standalone
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsv http://localhost:8081/health" ]
      interval: 2s
      timeout: 30s
      retries: 30
      start_period: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../test-utils/docker-setup/application.yml:/app/confs/application.yml:ro
      - ../../test-utils/docker-setup/application-secrets.yml:/app/secrets/application-secrets.yml:ro
    environment:
      MICRONAUT_CONFIG_FILES: /app/confs/application.yml,/app/secrets/application-secrets.yml
    ports:
      - "9904:8080"
