generatorName: java
inputSpec: /local/kestra-ee.yml
outputDir: /local/java/java-sdk

globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: true
  modelDocs: true
  skipFormModel: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false

library: apache-httpclient
invokerPackage: io.kestra.sdk.internal
modelPackage: io.kestra.sdk.model
apiPackage: io.kestra.sdk.api
groupId: io.kestra
artifactId: kestra-api-client
enumUnknownDefaultCase: true
useOneOfInterfaces: true
useJakartaEe: true

hideGenerationTimestamp: true
supportUrlQuery: false
useRuntimeException: true

typeMappings:
  PropertyDuration: String
  PropertyString: String
  PropertyBoolean: String
  PropertyDouble: String
  PropertyListString: String
  PropertyObject: String

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount|TestSuites|Apps|Dashboards|Files|Logs|Assets'