generatorName: go
inputSpec: /local/kestra-ee.yml
outputDir: /local/go-sdk/kestra_api_client

globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: true
  modelDocs: true
  skipFormModel: false

additionalProperties:
  packageName: kestra_api_client
  projectName: kestra_api
  withGoMod: false
  enumClassPrefix: true
  disallowAdditionalPropertiesIfNotPresent: false
  isGoSubmodule: true

gitUserId: kestra-io
gitRepoId: client-sdk/go-sdk

hideGenerationTimestamp: true

typeMappings:
  PropertyDuration: string
  PropertyString: string
  PropertyBoolean: string
  PropertyDouble: string
  PropertyListString: string
  PropertyObject: string

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount|TestSuites'