generatorName: python
inputSpec: /local/kestra-ee.yml
outputDir: /local/python/python-sdk

globalProperties:
  apiTests: true
  modelTests: false
  apiDocs: true
  modelDocs: true
  skipFormModel: false
hideGenerationTimestamp: true

additionalProperties:
  packageName: kestrapy
  projectName: "@kestra-io/kestrapy"
  packageAuthorEmail: "contact@kestra.io"
  disallowAdditionalPropertiesIfNotPresent: false
  customEmail: "contact@kestra.io"
  customAuthor: "Kestra.io"
  customDescription: "Kestra Python SDK"

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount'