generatorName: javascript
inputSpec: /local/kestra-ee.yml
outputDir: /local/javascript/javascript-sdk

globalProperties:
  apiTests: true
  modelTests: false
  apiDocs: true
  modelDocs: true
  skipFormModel: false

usePromises: true

hideGenerationTimestamp: true

additionalProperties:
  packageName: "@kestra-io/kestra-sdk"
  projectName: "@kestra-io/kestra-sdk"
  disallowAdditionalPropertiesIfNotPresent: false

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount|TestSuites'

typeMappings:
  Property_Object_: Object
  Property_Boolean_: Object
  Property_Double_: Object
  Property_Duration_: Object
  Property_List_String__: Object
  Property_String_: String