name: GO SDK tests

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/go-sdk

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5

      - name: build
        id: build
        run: go build .
