name: main.yml
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      skip-test:
        description: 'Skip test'
        required: false
        type: string
        default: "false"

jobs:
  file-changes:
    name: File changes detection
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      go: ${{ steps.changes.outputs.go }}
      java: ${{ steps.changes.outputs.java }}
      javascript: ${{ steps.changes.outputs.javascript }}
      python: ${{ steps.changes.outputs.python }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            go:
              - 'go-sdk/**'
            java:
              - 'java/**'
            python:
              - 'python/**'
            javascript:
              - 'javascript/**'
          token: ${{ secrets.GITHUB_TOKEN }}

  go:
    if: "needs.file-changes.outputs.go == 'true'"
    needs: file-changes
    uses: ./.github/workflows/go-sdk.yml
    secrets:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      APPLICATION_SECRETS: ${{ secrets.APPLICATION_SECRETS }}

  java:
    if: "needs.file-changes.outputs.java == 'true'"
    needs: file-changes
    uses: ./.github/workflows/java-sdk.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      APPLICATION_SECRETS: ${{ secrets.APPLICATION_SECRETS }}
  javascript:
    if: "needs.file-changes.outputs.javascript == 'true'"
    needs: file-changes
    uses: ./.github/workflows/javascript-sdk.yml
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      APPLICATION_SECRETS: ${{ secrets.APPLICATION_SECRETS }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  python:
    if: "needs.file-changes.outputs.python == 'true'"
    needs: file-changes
    uses: ./.github/workflows/python-sdk.yml
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      APPLICATION_SECRETS: ${{ secrets.APPLICATION_SECRETS }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}